# This is the experiment config file used for the fuzzbench service.
# Unless you are a fuzzbench maintainer running this service, this
# will not work with your setup.

trials: 20
max_total_time: 82800  # 23 hours, the default time for preemptible experiments.
cloud_project: fuzzbench
docker_registry: gcr.io/fuzzbench
cloud_compute_zone: us-central1-a
experiment_filestore: gs://fuzzbench-data
report_filestore: gs://www.fuzzbench.com/reports
cloud_sql_instance_connection_name: "fuzzbench:us-central1:postgres-experiment-db=tcp:5432"
preemptible_runners: true

# This experiment should generate a report that is combined with other public
# "production" experiments.
merge_with_nonprivate: true

# This experiment should be merged with other reports in later experiments.
private: false
