steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - gcr.io/fuzzbench/experiment-runner
  - --build-arg
  - BUILDKIT_INLINE_CACHE=1
  - --cache-from
  - gcr.io/fuzzbench/experiment-runner
  - -f
  - service/Dockerfile
  - .
- name: 'gcr.io/fuzzbench/experiment-runner'
  args: []
  env:
    - 'PULL_REQUEST_NUMBER=${_PR_NUMBER}'
  timeout: 1800s # 30 minutes
timeout: 1800s
