steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - gcr.io/fuzzbench/experiment-runner
    - --build-arg
    - BUILDKIT_INLINE_CACHE=1
    - --cache-from
    - gcr.io/fuzzbench/experiment-runner
    - -f
    - service/Dockerfile
    - .
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/fuzzbench/experiment-runner'
  args: []
  env:
    - 'PULL_REQUEST_NUMBER=${_PR_NUMBER}'
  secretEnv:
    - 'POSTGRES_PASSWORD'
  timeout: 1800s # 30 minutes
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/fuzzbench/secrets/POSTGRES_PASSWORD/versions/1
    env: 'POSTGRES_PASSWORD'
