benchmarks:
- curl_curl_fuzzer_http
- freetype2-2017
- harfbuzz-1.3.2
- jsoncpp_jsoncpp_fuzzer
- lcms-2017-03-21
- libjpeg-turbo-07-2017
- libpcap_fuzz_both
- libpng-1.2.56
- libxml2-v2.9.2
- libxslt_xpath
- mbedtls_fuzz_dtlsclient
- openssl_x509
- openthread-2019-12-23
- php_php-fuzz-parser
- proj4-2017-08-14
- re2-2014-12-09
- sqlite3_ossfuzz
- systemd_fuzz-link-parser
- vorbis-2017-12-11
- woff2-2016-05-06
- zlib_zlib_uncompress_fuzzer
cloud_compute_zone: us-central1-b
cloud_project: fuzzbench
cloud_sql_instance_connection_name: fuzzbench:us-central1:postgres-experiment-db=tcp:5432
concurrent_builds: 30
custom_seed_corpus_dir: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: 2022-11-22-02-33-15m-dongge
experiment_filestore: gs://fuzzbench-data
fuzzers:
- libfuzzer
git_hash: c0608813379f2dce012fcb59d2dd12f581f8bc30
local_experiment: false
max_total_time: 910
measurers_cpus: null
merge_with_nonprivate: true
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
preemptible_runners: true
private: false
region_coverage: false
report_filestore: gs://www.fuzzbench.com/reports
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
snapshot_period: 900
trials: 2
worker_pool_name: projects/fuzzbench/locations/us-central1/workerPools/buildpool
